osx_image: xcode11
language: objective-c
before_install:
  - set -o pipefail 
  - gem install xcpretty slather -N
  - xcrun instruments -w "iPhone 11 (13.0)" || echo "(Pre)Launched the simulator."
script:
  - xcodebuild -project Down.xcodeproj -scheme "Down" -destination "platform=iOS Simulator,name=iPhone 11,OS=13.0" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES test | xcpretty -c
after_success:
  - slather coverage --ignore "../**/*/Xcode*" --ignore "Source/cmark/*" --scheme "Down" Down.xcodeproj
